version: '3.8'
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./backend/node_modules
  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules
    stdin_open: true
    tty: true